parameters:
    api.url: '%env(API_URL)%'
    default_false: false
    api.debug: '%env(bool:default:default_false:API_DEBUG)%'
    default_locale: 'en'
    locale: '%env(string:default:default_locale:LOCALE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\UseCase\Sidebar\SidebarItemInterface:
            tags: [ 'app.sidebar_builder' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Request\ApiRequest:
        arguments:
            $apiBaseUrl: '%api.url%'
            $debug: '%api.debug%'

    App\Subscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%locale%'
